name = "LibML"
uuid = "be25e5fc-066e-40b8-ac16-2ae9c4d91289"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
