name = "LibML"
uuid = "be25e5fc-066e-40b8-ac16-2ae9c4d91289"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]
version = "0.2"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
julia = "1.9"
BSON = "0.3"
Flux = "0.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
